### ISSUE TITLE
Firefox 49 not able to use interact?

### ISSUE THREAD

**Issue by diego898** [ipython/ipywidgets#815] opened 2016-10-06 00:17 UTC
Im using macOS 10.12 (Sierra) and jupyter notebook 4.2.1 with python 3.5.2. I am trying to use interact from ipywidgets and the following code works perfectly in chrome 53 but **not** in firefox 49. Nothing shows up in my console, its just firefox does not show the interactive bars. How can I debug this to figure out if this something with the notebook or something with firefox? 

```
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter
import matplotlib.pyplot as plt
import numpy as np
from ipywidgets import interact, interactive, fixed, FloatSlider
import ipywidgets as widgets
from scipy.stats import multivariate_normal
%matplotlib inline

def plot_2dgauss(mu1,mu2,sig11,sig12,sig22):

    if(sig12 > sig11 and sig12 > sig22):
        sig12 = min(sig11,sig22)-0.1

    x, y = np.mgrid[-10:10:.25, -10:10:.25]
    pos = np.empty(x.shape + (2,))
    pos[:, :, 0] = x; pos[:, :, 1] = y
    rv = multivariate_normal([mu1, mu2], [[sig11, sig12], [sig12, sig22]])

    fig = plt.figure(figsize=(10,5))
    ax = fig.gca(projection='3d')         # set the 3d axes
    z = rv.pdf(pos)
    zmax = np.max(z)
    ax.plot_surface(x, y, z, 
                    rstride=2, 
                    cstride=2, 
                    alpha=0.5,
                    cmap=cm.BuPu)         # colour map

    cset = ax.contourf(x, y, z, 
                       zdir='z',          # direction to project the contour
                       offset=-zmax,        # how "far" render the contour map
                       cmap=cm.summer)    # winter colour map
    ax.set_zlim([-zmax,zmax])


interact(plot_2dgauss, 
        mu1=FloatSlider(min=-5, max=5, step=0.25,continuous_update=False),
        mu2=FloatSlider(min=-5, max=5, step=0.25,continuous_update=False),
        sig11=FloatSlider(min=1, max=15, step=0.25,continuous_update=False),
        sig22=FloatSlider(min=1, max=15, step=0.25,continuous_update=False),
        sig12=FloatSlider(min=0, max=15, step=0.25,continuous_update=False));
```

Note: I originally opened this at https://github.com/jupyter/notebook/issues/1789 but they recommended moving it over here.

**Comment by PhaethonPrime** [comment] 2016-10-10 20:37
I have the same issue with interact on Chrome: Version 53.0.2785.143 m (64-bit).

The example code online doesn't work:

```python
def f(x):
    return x

interact(f, x=10)
```

These are my versions:

    python                    3.5.2
    ipykernel                 4.3.1                    py35_0
    ipython                   4.2.0                    py35_0
    ipython_genutils          0.1.0                    py35_0
    ipywidgets                4.1.1                    py35_0
    jupyter                   1.0.0                    py35_3
    jupyter_client            4.3.0                    py35_0
    jupyter_console           4.1.1                    py35_0
    jupyter_core              4.1.0                    py35_0
    notebook                  4.2.1                    py35_0

**Comment by gnestor** [comment] 2016-10-21 15:45
@PhaethonPrime Can you both try upgrading to the current version of ipywidgets 5.2.2 and test again? I can verify that it's working on Chrome 54.0.2840.59.

**Comment by gnestor** [comment] 2016-10-21 15:49
@diego898 I just tested with Firefox 49, no problems. What version of ipywidgets are you running? You can check using `conda list` (if you are using Anaconda) or `pip show ipywidgets`.

**Comment by PhaethonPrime** [comment] 2016-10-21 16:09
Works fine at 5.2.2, same Chrome version that I mentioned.

**Comment by jasongrout** [comment] 2016-11-11 06:30
Master seems to work fine for me on Firefox 49:

<img width="386" alt="screen shot 2016-11-10 at 10 29 13 pm" src="https://cloud.githubusercontent.com/assets/192614/20206440/2cd13b56-a795-11e6-93ac-67a66f9224ec.png">

Can you tell us what ipywidgets commit you're at that doesn't work in Firefox 49? We're trying to reproduce this.

**Comment by jasongrout** [comment] 2016-12-06 19:32
Closing since there was no reply. Please reopen if you're still seeing an issue.

**Closed by jasongrout** 2016-12-06 19:32 UTC
Labels: environment, needs info
