### ISSUE TITLE
Static widgets

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipywidgets#16] opened 2015-05-05 20:30 UTC
Depends on #13 

Originally planned for 3.0, static widgets allow widgets to be exported using nbconvert.  The mechanism of state storage has yet to be decided.

**Comment by scottsievert** [comment] 2015-05-27 02:21
+1. If I'm interpreting correctly, it's a widget that you can embed on any webpage/get raw HTML. I would love to see this and am currently using the unsupported [ipywidgets].

[ipywidgets]:https://github.com/jakevdp/ipywidgets

**Comment by TMorville** [comment] 2015-10-21 13:11
+1. Using Nbconvert or Nbviewer with widgets would be neat feature for teaching people without access to ipython/jupyter.

**Comment by michaelaye** [comment] 2016-02-27 01:47
I'm confused, is it correct that currently nothing like this on Jake's blog is possible with the official ipywidgets? https://jakevdp.github.io/blog/2013/12/05/static-interactive-widgets/

**Comment by bcordo** [comment] 2016-04-20 11:39
This looks great. Looking forward!

**Comment by bcordo** [comment] 2016-04-20 11:58
This looks great guys btw. Looking forward!

**Comment by kulla** [comment] 2016-06-01 07:55
+1

**Comment by desilinguist** [comment] 2016-09-08 16:53
+1

**Comment by georgebv** [comment] 2016-09-18 18:33
https://github.com/jakevdp/ipywidgets-static
The problem is solved here, though native widgets look much batter. Is anyone working on this right now?

**Comment by GandaG** [comment] 2016-09-19 04:17
@georgebv You can tell from his own [example](https://github.com/jakevdp/ipywidgets-static/blob/master/example.ipynb) that it no longer works. Would absolutely love to see this feature though!

**Comment by sripakpa** [comment] 2016-09-20 22:47
+1

**Comment by sripakpa** [comment] 2016-09-20 23:16
How is the feature described in this ticket related/different from the feature to have interactive widgets embedded into static web pages illustrated [here](http://jupyter.org/embed-jupyter-widgets.html)?

**Comment by georgebv** [comment] 2016-09-20 23:32
The point is not having widgets in the static web page. It is about making them interact with the output (by storing all the possible output combinations in the html file).

**Comment by damianavila** [comment] 2016-09-21 13:09
I know @SylvainCorlay is going to write something (post) about this soon, see this comment: https://github.com/ipython/ipywidgets/issues/758#issuecomment-246200132

**Comment by tbsexton** [comment] 2016-09-26 16:52
Will be watching this; I have a reveal.js presentation .html file and would like an interactive slider/plot combination to be usable on my static site as opposed to only while using RISE.

**Comment by jbednar** [comment] 2016-11-15 19:27
@SylvainCorlay, can you confirm whether there will soon be static export of ipywidgets?  We're at this very moment trying to find a different widget library so that we can switch to it for that feature alone, but if we should be staying with ipywidgets and just need to hold on for a few days longer, please let us know!

**Comment by SylvainCorlay** [comment] 2016-11-15 19:33
Yes! There is already. For example on http://jupyter.org/widgets, widgets are live.

With 6.0 in a few days, widgets will also be embeddable in sphinx documentation.

Nbconvert will follow.

**Comment by jbednar** [comment] 2016-11-15 19:40
Great, thanks!  The live widgets at that link are great, but none of those are for the standard sliders, selection boxes, text entry boxes, etc. that we are using ipywidgets for. Presumably those are also now supported?  Nbconvert is indeed my main use case, but we can probably work with Sphinx if that's the only currently supported way.

**Comment by SylvainCorlay** [comment] 2016-11-15 19:42
All of these are supported. The widgets in that page are built upon `ipywidgets`. I will add a tab with some simple dropdowns and buttons.

We have had static widgets since 5.0. The nbconvert part is the only reason why this issue is not closed yet.

**Comment by jbednar** [comment] 2016-11-15 19:46
Sounds great.  Getting nbconvert support is crucial for people even to know that static support is available.  Presumably documentation is also needed before closing the issue?

**Comment by SylvainCorlay** [comment] 2016-11-15 19:49
Yes. We are currently formalizing the spec for the format of the serialized widgets. cf #901

**Comment by jbednar** [comment] 2016-11-15 19:57
With the goal of serialization being to generate and insert that HTML snippet directly, without user cutting and pasting?  That does sound crucial for this to be usable in practice, thanks.

**Comment by SylvainCorlay** [comment] 2016-11-15 20:00
I don't understand your question, but the html snippet feature will remain for those who want to embed in webpages, blogs.

The nbconvert question is more about the choice of how the widget state is stored in the notebook format.

**Comment by jbednar** [comment] 2016-11-15 20:08
I just mean that nbconvert converts .ipynb to .html, and presumably when one does so one won't need to paste in the HTML snippets that create the widgets, by hand?  Basically I just want the widgets to be preserved in the exported file, with the values they had at that time as their starting point, whether or not they are hooked up to anything that actually does something in the exported HTML.  E.g. here's an example of a bunch of ipywidgets generated with static PNGs using nbconvert: https://anaconda.org/jbednar/paramnb/notebook

But that only works because of the embedded PNGs, whereas embedding the actual widgets would be so much cleaner.  Basically I just want to be able to save things as .html and have it all work, insofar as it is possible. Perhaps @philippjfr and @jlstevens could explain better.

**Comment by SylvainCorlay** [comment] 2016-11-15 20:12
👍 got that. Stay tuned. :)

**Comment by jbednar** [comment] 2016-11-15 20:16
Fabulous!  I'll hand you a drink as you sprint by, if I see you!

**Comment by jbednar** [comment] 2016-12-08 19:24
How is the sprint coming?  You guys must be winded by now if you've been running flat out for this long! :-)

**Comment by SylvainCorlay** [comment] 2016-12-09 08:35
@jbednar 

- we have working static widgets in sphinx docs

  ![nbsphinx-screencast](https://cloud.githubusercontent.com/assets/2397974/20971580/41b0af4a-bc92-11e6-9066-d95b3282fe60.gif)

  which is only waiting for the PR to get merged in another repo.

 - All the pieces are completed for nbviewer except an outstanding PR in nbconvert.

**Comment by jbednar** [comment] 2016-12-09 16:28
That sounds great. Can't wait!

**Comment by michaelaye** [comment] 2016-12-09 17:21
Very nice. Just a quickie: i assume the readthedocs version is not yet working because of some final tweaks or am I maybe missing a plugin (using Safari on 10.11.6)?
![screenshot 2016-12-09 10 20 59](https://cloud.githubusercontent.com/assets/69774/21058016/3f39e84a-bdf9-11e6-99fb-1eb9cf43d784.png)

**Comment by SylvainCorlay** [comment] 2016-12-09 17:33
Indeed, stay tuned for the rtd rendering.

**Comment by SylvainCorlay** [comment] 2016-12-11 11:35
Widgets are rendering in RTD http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html

**Comment by akhmerov** [comment] 2016-12-11 13:08
Wow, nice! Out of curiousity, what is the chosen mechanism for state storage?

**Comment by SylvainCorlay** [comment] 2016-12-11 14:52
@akhmerov check out the section of the documentation on embedding that got improved at the same time.

http://ipywidgets.readthedocs.io/en/latest/embedding.html

**Comment by michaelaye** [comment] 2016-12-11 18:53
Looks great!
But: The linked widgets are not linked in RTD:
http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Basics.html#Linking-two-similar-widgets

**Comment by SylvainCorlay** [comment] 2016-12-11 19:05
@michaelaye anything that requires a roundtrip to the backend will not work.

However, `jslink` and `jsdlink` do work on RTD.

**Comment by SylvainCorlay** [comment] 2016-12-11 19:14
@michaelaye for things that require a kernel, we are thinking of using mybinder as a kernel provider (without the notebook) for embedded widgets. I got some example working but the documentation would probably not be the main purpose.

**Closed** 2016-12-14 14:13 UTC
Labels: proposal

**Comment by SylvainCorlay** [comment] 2016-12-14 14:15
We now support widgets rendering on nbviewer

Example here: http://nbviewer.jupyter.org/github/ipython/ipywidgets/blob/master/docs/source/examples/Widget%20Events.ipynb

This requires the widgets to be generated from the ipywidgets 6.0 (beta) or the current state of master and will be included in the next release.

**Comment by SylvainCorlay** [comment] 2016-12-14 14:17
Really really glad to solve this issue. Support of custom widgets and some css glitches will be worked on before the 6.0.

Thank you to everyone involved. @minrk @michaelpacer @jasongrout @takluyver @jdfreder.

**Comment by inodb** [comment] 2016-12-21 20:25
@SylvainCorlay Great stuff! Thanks so much for your work on this!

One question: in the nbviewer link at the top if I click on the button or hit enter in the submit field nothing happens. Is that expected? Thanks!

**Comment by SylvainCorlay** [comment] 2016-12-21 21:20
Yes. In these static embeddings, there is no python backend. Only the pure js things will work.

We are also working on a kernel-backed thing for full fledges apps.

**Comment by inodb** [comment] 2016-12-21 21:31
Gotcha! One more question: Is it possible to change plots using a radio button or a slider? Similar to http://nbviewer.jupyter.org/github/jakevdp/ipywidgets/blob/master/example.ipynb#Example-4:-Matplotlib-Figures

**Comment by dmadeka** [comment] 2016-12-21 21:43
You can check www.github.com/Bloomberg/bqplot .. its built for doing things like this

----- Original Message -----
From: Ino de Bruijn <reply@reply.github.com>
To: ipywidgets@noreply.github.com
CC: subscribed@noreply.github.com
At: 21-Dec-2016 14:31:52


Gotcha! One more question: Is it possible to change plots using a radio button or a slider? Similar to http://nbviewer.jupyter.org/github/jakevdp/ipywidgets/blob/master/example.ipynb#Example-4:-Matplotlib-Figures
