### ISSUE TITLE
Examples of widget events in docs do not match their description 

### ISSUE THREAD

**Issue by michaelpacer** [ipython/ipywidgets#988] opened 2016-12-14 19:37 UTC
In https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Events.html there are examples of widgets that say (for example):

> The values of range1 and range2 are synchronized

But then, the values are not synchronized.

I'm guessing that this is because the state of the widgets is separate from the functionality and that that might need to be exposed separately? Since there are javascript interpretations of the functionality in some cases (e.g., `dl = widgets.jsdlink((source_range, 'value'), (target_range1, 'value'))`) I could imagine that that's possible, but also potentially difficult.

**Comment by SylvainCorlay** [comment] 2016-12-14 19:57
This is because the synchronization happens on the python side with traitlets.link.  Interactions that require a roundtrip to the python side won't work in sphinx documentation. We will need to reformulate the doc to not be confusing now that widgets are live.

**Comment by SylvainCorlay** [comment] 2017-01-03 12:39
Closing since it is not a bug per se...

**Comment by jasongrout** [comment] 2017-01-03 23:28
Re-opening so we can clarify the docs.

**Closed** 2017-01-03 23:35 UTC
