### ISSUE TITLE
display='none' has no effect with children Accordion's children

### ISSUE THREAD

**Issue by hainm** [ipython/ipywidgets#741] opened 2016-08-29 17:04 UTC
Hi,

Please see below.

![acc](https://cloud.githubusercontent.com/assets/4451957/18059854/fa6e3d84-6de8-11e6-8271-a69f36c31c23.png)

Code

[tmpnb_ngl.txt](https://github.com/ipython/ipywidgets/files/442961/tmpnb_ngl.txt)

**Comment by hainm** [comment] 2016-08-29 17:04
If I us `Tab`, I got what I expected (hiding 3rd 'z' widget)

**Comment by hainm** [comment] 2016-08-30 03:34
I am using v5.2.2, not dec version.

**Comment by gnestor** [comment] 2016-10-24 16:03
`widget.children[-1]` is a `ipywidgets.widgets.widget_output.Output` class vs. a `ipywidgets.widgets.widget_int.IntSlider`, so setting the display value of that will not affect the 3rd slider. 

![image](https://cloud.githubusercontent.com/assets/512354/19653034/d42ddaac-99c7-11e6-8e31-a5703a5bd88f.png)

So, `widget.children[-2].layout.display = 'none'` will hide the 3rd slider. I suggest using the `visibility` property primarily because according to [the docs](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html#Properties-of-the-parent), display "must be equal to ‘flex’ or ‘inline-flex’", although `display = 'none'` will work.

**Comment by hainm** [comment] 2016-10-24 17:39
@gnestor I meant is the behavior is different between using Tab and Accordion. With `Tab`, I can set `display=None` while I can not with `Accordion`. I don't see why they should be different.

There is a reason I want to use `display=None` in this case: Supposed I have an `widget` that is about 1/4-1/2 of the notebook. Using `visibility` does not collapse it if user does not need it, so there will be wasted blank page. Using `display=None` will collapse that.

**Comment by jasongrout** [comment] 2016-10-24 17:53
This looks like a bug in the Tab widget, that it's hiding the wrong widget. Looks like the bug is already fixed in master, though:

<img width="615" alt="screen shot 2016-10-24 at 1 52 34 pm" src="https://cloud.githubusercontent.com/assets/192614/19657216/327e7872-99f1-11e6-9e94-95b2ac069712.png">

Changing the line to `widget.children[-2].layout.display='none'` works as expected, though, and it hides the z slider.

**Comment by jasongrout** [comment] 2016-10-24 18:01
Closing since it seems to be fixed in master. Please reopen if doing `.children[-2]` as above doesn't work for you.

**Comment by gnestor** [comment] 2016-10-24 18:10
@jasongrout I can verify that Accordion is not responding to changes to its children's layout. I created [a test notebook](https://gist.github.com/gnestor/29433f308eeb6c09ca52e1650a705eed) to reproduce.

![image](https://cloud.githubusercontent.com/assets/512354/19657622/d8fd493e-99d9-11e6-9200-9d738275353a.png)

**Comment by jasongrout** [comment] 2016-10-24 18:43
I'll see your screenshot and raise you one of my own notebook :)

<img width="566" alt="screen shot 2016-10-24 at 2 40 51 pm" src="https://cloud.githubusercontent.com/assets/192614/19658982/19661faa-99f8-11e6-8ecc-366b0652338a.png">

The accordion you show in your screenshot is not the one we recently merged, I think - the 'Page 0' is blue in the old accordion, but plain black in the new rewrite.

**Comment by gnestor** [comment] 2016-10-24 19:14
You called my bluff! I was wondering why the tabs were still looking like before. Ok, verified that it's currently working as expected master.

**Closed by gnestor** 2016-10-24 19:14 UTC
Labels: bug
