### ISSUE TITLE
Improve @interact API

### ISSUE THREAD

**Issue by jdemeyer** [ipython/ipywidgets#238] opened 2015-11-12 23:33 UTC
There are various issues and unexpected behaviours with `@interact`:
 
**1.** code like
```
@interact
def f(x=[2,5]):
```
should produce some widget with two values, namely 2 and 5. It currently gives a slider with values from 2 to 5. Should the current behaviour be deprecated or just changed directly?

**2.** More generally,
```
@interact
def f(x=[obj1,obj2,obj3]):
```
should produce a widget where you can choose between `obj1`, `obj2` and `obj3`. This currently works for strings only.

**3.** Use the [collections abc](https://docs.python.org/2/library/collections.html#collections-abstract-base-classes). In particular, support generator expressions and `OrderedDict`.

**Comment by SylvainCorlay** [comment] 2015-11-12 23:52
Talked to @jdemeyer in person and I totally agree that we should make `@interact` more similar to the one of Sage, which has been around for a while and has a lot of users.

**Comment by ellisonbg** [comment] 2015-11-13 00:02
On Thu, Nov 12, 2015 at 6:33 PM, jdemeyer <notifications@github.com> wrote:

> There are various issues and unexpected behaviours with @interact:
>
> *1.* code like
>
> @interact
> def f(x=[2,5]):
>
> should produce some widget with two values, namely 2 and 5. It currently
> gives a slider with values from 2 to 5. Should the current behaviour be
> deprecated or just changed directly?
>
I don't follow the "should" here. We designed the widget abbreviation
syntax very carefully. The two-and-three-element list of int/float syntax
follows that of Mathematica for sliders. Selection widgets are dicts to
allow users to provide display/value pairs.



> *2.* More generally,
>
> @interact
> def f(x=[obj1,obj2,obj3]):
>
> should produce a widget where you can choose between obj1, obj2 and obj3.
> This currently works for strings only.
>
Same as comment above - this is by design.

Can you provide more details of what you are thinking about when you make
these recommendations?



> *3.* Use the
> https://docs.python.org/2/library/collections.html#collections-abstract-base-classes
> <http://collections%20abc>. In particular, support generator expressions
> and OrderedDict.
>
Hmm, this web page isn't resolving for me right now...


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/238>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdemeyer** [comment] 2015-11-13 00:09
> We designed the widget abbreviation syntax very carefully.

Well, I think that SageMath designed them **even more** carefully then.

> The two-and-three-element list of int/float syntax follows that of Mathematica for sliders.

You already support that using *tuples*. Do you really need to do the same for *lists*?

I find it very counter-intuitive that the following two do something completely different:
```python
@interact
def f(x=[1, 2, 3]): pass

@interact
def g(x=['1', '2', '3']): pass
```

**Comment by jdemeyer** [comment] 2015-11-13 00:15
> Can you provide more details of what you are thinking about when you make these recommendations?

It could really be anything. You just have a list of objects and want the user to select one of them. You can still use the string representation to display those objects in the dropdown.

This could go from the list of prime of numbers less than 100 (*) to the list of elliptic curves defined over a given finite field.

(*) Ideally, this would be a slider instead of a dropdown.

**Comment by jdemeyer** [comment] 2015-11-13 00:17
> Hmm, this web page isn't resolving for me right now...

I messed up my markdown. It's fixed now.

**Comment by ellisonbg** [comment] 2015-11-13 00:20
On Thu, Nov 12, 2015 at 7:09 PM, jdemeyer <notifications@github.com> wrote:

> We designed the widget abbreviation syntax very carefully.
>
> Well, I think that SageMath designed them *even more* carefully then.
>

I wasn't in any way implying that Sage didn't design its syntax as
carefully. Sage has different design constraints compared to
Python/IPython, so I am not surprised different choices were optimal for
the two.

IIRC, Sage invented new syntax that isn't valid Python (0..12) for their
slider abbreviation. That is definitely not an option for us. What do you
propose instead of using lists/tuples of float/int for sliders?


> The two-and-three-element list of int/float syntax follows that of
> Mathematica for sliders.
>
> You already support that using *tuples*. Do you really need to do the
> same for *lists*?
>
> I find it very counter-intuitive that the following two do something
> completely different:
>
> @interactdef f(x=[1, 2, 3]): pass
> @interactdef g(x=['1', '2', '3']): pass
>
> Are you proposing that list and tuples be used for different things
(slider versus selection)? I don't think that mutability has anything to do
with this and that choice would be difficult to explain or remember.

What about using a Python set for a selection object? That does make sense
in that a selection control (at least the simple kind) doesn't usually
allow for repeats?

Brian



> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/238#issuecomment-156276598>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment] 2015-11-13 00:21
I am fine using the collections ABCs you point to where they make sense.

On Thu, Nov 12, 2015 at 7:19 PM, Brian Granger <ellisonbg@gmail.com> wrote:

>
>
> On Thu, Nov 12, 2015 at 7:09 PM, jdemeyer <notifications@github.com>
> wrote:
>
>> We designed the widget abbreviation syntax very carefully.
>>
>> Well, I think that SageMath designed them *even more* carefully then.
>>
>
> I wasn't in any way implying that Sage didn't design its syntax as
> carefully. Sage has different design constraints compared to
> Python/IPython, so I am not surprised different choices were optimal for
> the two.
>
> IIRC, Sage invented new syntax that isn't valid Python (0..12) for their
> slider abbreviation. That is definitely not an option for us. What do you
> propose instead of using lists/tuples of float/int for sliders?
>
>
>> The two-and-three-element list of int/float syntax follows that of
>> Mathematica for sliders.
>>
>> You already support that using *tuples*. Do you really need to do the
>> same for *lists*?
>>
>> I find it very counter-intuitive that the following two do something
>> completely different:
>>
>> @interactdef f(x=[1, 2, 3]): pass
>> @interactdef g(x=['1', '2', '3']): pass
>>
>> Are you proposing that list and tuples be used for different things
> (slider versus selection)? I don't think that mutability has anything to do
> with this and that choice would be difficult to explain or remember.
>
> What about using a Python set for a selection object? That does make sense
> in that a selection control (at least the simple kind) doesn't usually
> allow for repeats?
>
> Brian
>
>
>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ipython/ipywidgets/issues/238#issuecomment-156276598>
>> .
>>
>
>
>
> --
> Brian E. Granger
> Associate Professor of Physics and Data Science
> Cal Poly State University, San Luis Obispo
> @ellisonbg on Twitter and GitHub
> bgranger@calpoly.edu and ellisonbg@gmail.com
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdemeyer** [comment] 2015-11-13 00:38
> What do you propose instead of using lists/tuples of float/int for sliders?
I propose tuples, not lists.

**Comment by jdemeyer** [comment] 2015-11-13 00:44
In short, I propose that
```
@interact
def f(x=[obj1,obj2,obj3]): pass
```
always gives you a widget giving a choice between `obj1`, `obj2`, `obj3`, regardless of the types of these objects.

The actual visualization of that widget (slider, push buttons, dropdown box) is a different discussion.

**Comment by jdemeyer** [comment] 2015-11-13 00:47
> What about using a Python set for a selection object? That does make sense in that a selection control (at least the simple kind) doesn't usually allow for repeats?

Sure, it makes sense to support that (and it will be if you support `collections` correctly). But it shouldn't be the only supported way, since a set is unordered.

**Comment by jdemeyer** [comment] 2015-12-18 07:14
Any comments?

**Closed** 2016-01-20 12:11 UTC
Labels: proposal
