### ISSUE TITLE
Notebook JSON is invalid

### ISSUE THREAD

**Issue by jdemeyer** [ipython/ipywidgets#1003] opened 2017-01-02 21:27 UTC
Something just corrupted a Jupyter notebook that I use for testing. This is a fairly big and complicated notebook with lots of ipywidgets. More importantly, the problem is fixed by executing Cell -> All Output -> Clear

Relevant versions (installed within SageMath):
- python 2.7.12
- traitlets 4.2.2
- jupyter_core 4.1.0
- jupyter_client 4.3.0
- ipykernel 4.3.1
- ipython 5.1.0
- notebook 4.2.1
- ipywidgets 6.0.0.beta5
- widgetsnbextension 2.0.0b7

After saving, I suddenly got the error
```
[E 21:54:37.680 NotebookApp] Notebook JSON is invalid: {u'model_id': u'218ae5cdec504d24bb3ddab6b38a13c5'} is not valid under any of the given schemas
    
    Failed validating u'oneOf' in schema[u'properties'][u'data'][u'patternProperties'][u'^(?!application/json$)[a-zA-Z0-9]+/[a-zA-Z0-9\\-\\+\\.]+$']:
        {u'oneOf': [{u'type': u'string'},
                    {u'items': {u'type': u'string'}, u'type': u'array'}]}
    
    On instance[u'data'][u'application/vnd.jupyter.widget-view+json']:
        {u'model_id': u'218ae5cdec504d24bb3ddab6b38a13c5'}
```

Despite this, the notebook seems to function correctly.

**Comment by SylvainCorlay** [comment] 2017-01-02 21:29
We now depend on nbformat 4.2.0!

**Comment by jdemeyer** [comment] 2017-01-02 21:46
If you do, the error message should be clearer :-)

**Comment by jasongrout** [comment] 2017-01-02 22:13
The error is from nbformat, iirc, not ipywidgets. Are you running on master, and did you install it? The dependency list should pull in the correct version of nbformat, or complain loudly at install time.

**Comment by SylvainCorlay** [comment] 2017-01-02 22:33
> If you do, the error message should be clearer :-)

The fact that this was not valid was a bug in nbformat 4.1, which was fixed in 4.2.

**Comment by SylvainCorlay** [comment] 2017-01-02 22:34
> The error is from nbformat, iirc, not ipywidgets. Are you running on master, and did you install it? The dependency list should pull in the correct version of nbformat, or complain loudly at install time.

I imagine that @jdemeyer has a dev install and updated from master!

Closing !

**Closed by SylvainCorlay** 2017-01-02 22:34 UTC

**Comment by jdemeyer** [comment] 2017-01-03 07:46
> Are you running on master, and did you install it? The dependency list should pull in the correct version of nbformat, or complain loudly at install time.

Yes, I did install the package using `pip`. Unfortunately, due to certain issues with `pip` (I don't know the details), we had to disable `pip`'s dependency checking within Sage.

**Comment by jasongrout** [comment] 2017-01-03 23:39
> we had to disable pip's dependency checking within Sage.

This does ring a bell. Regardless, sounds like the issue is that the dependency is ignored.

**Comment by Cruig** [comment] 2017-03-24 00:36
Installed ipywidgets from `conda install` with a fresh install of anaconda and ran into this today. Same solution of clearing output for the problem cell fixed the issue.

**Comment by jasongrout** [comment] 2017-03-24 00:53
@Cruig - what does `conda list` give, especially versions of nbformat, ipywidgets, and widgetsnbextension?
