### ISSUE TITLE
HBox widget does not show with versions >6.0.0.beta3

### ISSUE THREAD

**Issue by DeepVoltaire** [ipython/ipywidgets#998] opened 2017-01-01 17:15 UTC
I tried using the newest versions and noticed that in addition to a new error (the widgets show nevertheless)

`The installed widget Javascript is the wrong version. It must satisfy the semver range ^2.0.9.`

all versions after 6.0.0.beta3 do no show the simple HBox widget 

`import ipywidgets as widgets`
`items = [widgets.Label(str(i)) for i in range(4)]`
`widgets.HBox(items)`

**Comment by SylvainCorlay** [comment] 2017-01-02 14:26
I think that you have a conflicting other version of the javascript hanging around in one of the jupyter directories.

**Comment by SylvainCorlay** [comment] 2017-01-03 10:27
Closing since I cannot reproduce in either jupyterlab or notebook.

**Closed by SylvainCorlay** 2017-01-03 10:27 UTC

**Comment by DeepVoltaire** [comment] 2017-01-03 10:42
Thanks for your answers! What can I try to fix this?

**Comment by SylvainCorlay** [comment] 2017-01-03 13:17
I recommend that you check out the `data` paths listed in in the output of `jupyter --paths` if you have an older version of the javascript hanging around.

**Comment by jasongrout** [comment] 2017-01-03 21:55
In notebook 4.3.1, you can start the server with `--debug` and it will print out the path on disk it is serving any javascript files from. That helps tremendously in tracking down problems like this where you may have multiple installations of the javascript.

`jupyter notebook --debug`

Then go to a notebook page that loads the widget javascript and look in the server logs for where it is serving the widget javascript from.

**Comment by jasongrout** [comment] 2017-01-03 23:27
Look for the line that says:

`Path jupyter-js-widgets/extension.js served from ...`

and see if that path is what you are expecting.
