### ISSUE TITLE
ToggleButtons aren't entirely working

### ISSUE THREAD

**Issue by ellisonbg** [ipython/ipywidgets#223] opened 2015-11-01 23:51 UTC
I my playing around with the `ToggleButtons` I have found that simple unfocusing the set of buttons will delect all of them. The selected button should remain selected even when other elements on the page are focused. At least one of them has to be selected for this UI to make sense. and that is not currently true.

**Comment by afshin** [comment] 2016-04-04 20:06
The `ToggleButtons` behavior needs some review. In the newly reimplemented `6.x` version of `ToggleButtons`, the specific issue you point out is resolved. However, when the set of toggles is instantiated, they all have the `button_style` they were given at instantiation. Immediately upon one of the toggles being activated, all buttons are reset to the default button style (although the toggling action works just fine). This is the behavior I implemented because the earlier behavior seemed confusing. But I'll open a separate issue to ask for another look at the expected behavior of this widget.

**Comment by SylvainCorlay** [comment] 2016-06-26 02:10
Fixed in #645

**Closed by SylvainCorlay** 2016-06-26 02:10 UTC
Labels: bug
