### ISSUE TITLE
@interact + select does not respect default value from function signature.

### ISSUE THREAD

**Issue by Carreau** [ipython/ipywidgets#226] opened 2015-11-04 23:39 UTC
Not sure if it's a bug, but seem users expect the following ...

``` python
from ipywidgets import interact
from ipywidgets.widgets import Select

@interact(v=Select(options=['a','b']))
def function(v='b'):
    print(v)
```

To print `b`, it prints `a`:

![screen shot 2015-11-04 at 15 36 42](https://cloud.githubusercontent.com/assets/335567/10955637/19ef825a-830a-11e5-9b40-1c45e186d935.png)

Setting value in the options explicitely works. 

Real example is of course more complex...

**Comment by jasongrout** [comment] 2016-11-11 23:36
A design question: what should the default be in this case, where an int slider is created?

```python
@interact(x=5)
def f(x=1):
    print(x)
```

Before, `x=5` was the default, but now `x=1` is the default. Which should it be?

**Comment by jasongrout** [comment] 2016-11-11 23:38
Some design questions are over on the PR at #891.

**Comment by jasongrout** [comment] 2016-11-11 23:54
In addition to some issues with extending this idea noted in #891, how about this example?

```python
from ipywidgets import interact
from ipywidgets.widgets import Select

@interact(v=Select(options=['a','b'], value='a'))
def function(v='b'):
    print(v)
```

Should that default to a? I think so, but we can't distinguish that from the example in the OP. That makes me think that the answer to this issue is 'no, the appropriate way to set a default when giving a widget is to set the value in the widget'. @Carreau, thoughts?

**Comment by jasongrout** [comment] 2016-11-15 18:55
@Carreau, @SylvainCorlay - I propose we close this as not implemented by design, given the example above. Thoughts?

**Comment by SylvainCorlay** [comment] 2016-11-15 18:57
Sounds good to me.

**Comment by jasongrout** [comment] 2016-11-15 19:48
Thanks. Closing this as by design. If you'd like to set the default for an explicit widget, please explicitly set the default in the widget creation.

Another reason for not doing this is that if we are sharing a widget among different interacts, it gets really confusing what the value is if it is being set every time a new interact is called.

Please re-open if anyone has further arguments for why we should do this. I'm happy to discuss further.

**Closed by jasongrout** 2016-11-15 19:48 UTC
Labels: bug, discussion
