### ISSUE TITLE
Dropdown widget : error on option update

### ISSUE THREAD

**Issue by patrickhoebeke** [ipython/ipywidgets#575] opened 2016-05-11 08:54 UTC
Hello,

I've just updated to version 5.1.3
Updating the option values raises an error now (TraitError: Invalid selection). See example below.
```python
from IPython.display import display
from ipywidgets import widgets
dpdown=widgets.Dropdown(description='example',options=['1','2','3'])
dpdown.options=['4','5','6']
display(dpdown)
```
Apparently it is because the new list of options does not contains the current value, as this works:
```python
from IPython.display import display
from ipywidgets import widgets
dpdown=widgets.Dropdown(description='example',options=['1','2','3'])
dpdown.options=['3','5','6']
display(dpdown)
```

The current work-around I found is this:
```python
from IPython.display import display
from ipywidgets import widgets
dpdown=widgets.Dropdown(description='example',options=['1','2','3'])
with dpdown.hold_trait_notifications():
    dpdown.options=['4','5','6']
display(dpdown)
```
I am not sure it is the best approach but at least it works :-)
What do you think ?

Patrick

**Comment by SylvainCorlay** [comment] 2016-06-26 02:51
Sorry for the late reply. This is the correct workaround. Next version of widgets will choose an arbitrary value on update of options. In the meantime. You are doing the right thing.

There is another issue (#621) which is a duplicate of this one. Although I close this one since there has been more discussions in #621.

**Closed by SylvainCorlay** 2016-06-26 02:51 UTC
