### ISSUE TITLE
Button visibility in HBox: not working

### ISSUE THREAD

**Issue by clupascu** [ipython/ipywidgets#757] opened 2016-09-07 15:28 UTC
Hello,

It seems that the visibility of a Button in an HBox is not working.
Even when I set up the visibility to False the button is still displayed (and the Button.visible returns False).
I think it is a bug. Could you confirm ?

have a nice day !

![schermata 2016-09-07 alle 17 27 11](https://cloud.githubusercontent.com/assets/22050958/18318079/7e24e1e4-7520-11e6-88ef-cd722f60a097.png)

**Comment by dmadeka** [comment] 2016-09-07 15:41
`visible` is a deprecated attribute. Try `mybox.children[1].display = 'none'`. Or on initialization pass a `Layout` object with `display='none'`

**Comment by dmadeka** [comment] 2016-09-07 15:41
See #710

**Comment by SylvainCorlay** [comment] 2016-09-07 15:42
@dmadeka you missed `layout` in the code above

**Comment by clupascu** [comment] 2016-09-08 15:00
Thank you!

**Comment by SylvainCorlay** [comment] 2016-09-08 15:04
Closing since duplicate on top-level attribute regression issue!

**Closed by SylvainCorlay** 2016-09-08 15:04 UTC
