### ISSUE TITLE
adding autocompletion for Dropdown? 

### ISSUE THREAD

**Issue by hainm** [ipython/ipywidgets#694] opened 2016-08-01 20:15 UTC
this issue is closely relates to #692. The difference here is for Dropdown.

For example, if user wants to make a Dropdown of all US states. If he/she wants to choose New York, just type 'N'.

**Comment by jasongrout** [comment] 2016-11-08 19:18
This sounds like a great idea.

**Comment by jasongrout** [comment] 2016-11-08 19:41
Duplicate of #574.

**Closed by jasongrout** 2016-11-08 19:41 UTC
Labels: feature request
